### ISSUE TITLE
PRADO REQUEST 

### ISSUE THREAD

**Issue by Isabel-Lifu-211207-XPrado** [TurnipGuy30/Pokemon-PythonRed#6]
**Describe what you want to be added**
A new location? More customisation?
Prado Pokémon 
(If your feature request is related to a problem, please create a Bug Report Issue instead.)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. What implementation options do we have?
Animal type: Golden retriever
Gender: Male
Personality: Nice, easy-going, adorable
**Reasoning behind the request**
Why should this be considered? Is it a mechanic from another Pokémon game? Would it make the game more playable?
BECAUSE, IT'S A PRADO!!!
**Additional context**

**Comment by Isabel-Lifu-211207-XPrado** [comment]
Thank you Johnny SD

**Comment by TurnipGuy30** [comment]
Okay! This will be added in eventually. Thanks for the request!
