### ISSUE TITLE
How can I use this in Ubuntu

### ISSUE THREAD

**Issue by anonygituser** [TurnipGuy30/Pokemon-PythonRed#7]

**Comment by JeremyLARDENOIS** [comment]
Hello, seeing your issue, i created a fork here <https://github.com/JeremyLARDENOIS/Pokemon-PythonRed> based on the last commit. Let me know if all is ok. Enjoy !

**Comment by TurnipGuy30** [comment]
Thanks @JeremyLARDENOIS!

**Comment by JeremyLARDENOIS** [comment]
You're welcome. If you want the pull request, don't hesitate, just ask. And if you need help for some feature create issues and i will have a look. ^-^

**Comment by TurnipGuy30** [comment]
It's nice to have a collaborator to help, thanks so much!

**Comment by TurnipGuy30** [comment]
From now on, both Windows and Linux are supported from this one branch.
